# Generated by Django 3.2.8 on 2022-05-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Text Field')),
                ('image', models.ImageField(upload_to='image/upload/codex/%y/%m/%d/')),
            ],
        ),
    ]
