# Generated by Django 3.0 on 2022-05-20 19:48

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='body_default',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='body_editorjs_text',
            field=django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='content',
            field=models.TextField(blank=True, default='Text Field', null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/upload/codex/%y/%m/%d/'),
        ),
    ]
