# Generated by Django 3.0 on 2022-05-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220520_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='body_editorjs',
        ),
    ]
