# Generated by Django 3.0 on 2022-05-21 17:05

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_uploadimage_body_editorjs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
